#!/bin/bash

if [ -z "$CONTAINER_NAME" ]; then
  CONTAINER_NAME=gameon_dev_etcd0
  echo "Defaulting Container name to $CONTAINER_NAME"
fi


CONTAINERS=$(docker ps -a | grep $CONTAINER_NAME)
if [ -n "$CONTAINERS" ]; then
  docker stop -t 0 $CONTAINER_NAME
  docker wait $CONTAINER_NAME
  docker rm $CONTAINER_NAME
  CONTAINERS=$(docker ps -a | grep $CONTAINER_NAME)
  while [ -n "$CONTAINERS" ]; do
    echo "Container not yet removed, got (${CONTAINERS})"
    CONTAINERS=$(docker ps -a | grep $CONTAINER_NAME)
    sleep 10
  done
fi


docker run -d \
  --name=$CONTAINER_NAME \
  -e "ETCD_NAME=${CONTAINER_NAME}" \
  --volume=${CONTAINER_NAME}_data:/data \
  registry.eu-gb.bluemix.net/gameontext/gameon-etcd:v2.2.4

CONTAINERS=$(docker ps | grep $CONTAINER_NAME | grep Running)
while [ -z "$CONTAINERS" ]; do
  echo "Container not yet running, got (${CONTAINERS})"
  CONTAINERS=$(docker ps | grep $CONTAINER_NAME | grep Running)
  sleep 10
done
