apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: gameon-system
  labels:
    app: {{ .Chart.Name}}-ingress
    {{- include "gameon-system.labels" . }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- if .Values.coreServices }}
    - http:
        paths:
        {{- range .Values.coreServices }}
        - path: {{ .path }}
          backend:
            serviceName: {{ .serviceName }}-service
            servicePort: {{ .servicePort }}
        {{- end }}
  {{- end }}
  {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- range .services }}
        - path: {{ .path }}
          backend:
            serviceName: {{ .Chart.Name }}-{{ .serviceName }}
            servicePort: {{ .servicePort }}
        {{- end }}
  {{- end }}
