{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: gameon-system
  labels:
    app: {{ .Chart.Name}}-ingress
    {{- include "gameon-system.labels" . }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}

spec:
{{- with .Values.ingress.backend }}
  backend:
    serviceName: {{ .serviceName }}
    servicePort: {{ .servicePort }}
{{- end }}
# TLS block causes automatic redirection of http -> https
  tls:
    - hosts:
      - {{ .Values.global.frontDoor }}
{{- with .Values.ingress.secretName }}
      secretName: {{ . }}
{{- end }}
  rules:
    - host: {{ .Values.global.frontDoor }}
      http:
        paths:
        {{- range .Values.coreServices }}
        {{- if eq (.skipIngress | default false) false }}
        - path: {{ .path }}
          backend:
            serviceName: {{ .serviceName }}-service
            servicePort: {{ .servicePort }}
        {{- end }}
        {{- end }}
{{- end }}
