{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: gameon-system
  labels:
    app: {{ .Chart.Name}}-ingress
    {{- include "gameon-system.labels" . }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}

spec:
{{- with .Values.ingress.backend }}
  defaultBackend:
    service:
      name: {{ .serviceName }}
      port:
        number: {{ .servicePort }}
{{- end }}
# TLS block causes automatic redirection of http -> https
  tls:
    - hosts:
      - {{ .Values.global.frontDoorHost }}
      - {{ .Values.global.frontDoorAltHost }}
{{- with .Values.ingress.secretName }}
      secretName: {{ . }}
{{- end }}
  rules:
    - host: {{ .Values.global.frontDoorHost }}
      http:
        paths:
        {{- range .Values.coreServices }}
        {{- if eq (.skipIngress | default false) false }}
        - path: {{ .path }}
          pathType: Prefix
          backend:
            service:
              name: {{ .serviceName }}
              port:
                number: {{ .servicePort }}
        {{- end }}
        {{- end }}
#TODO: values for auth really should come from values.
    - host: {{ .Values.global.frontDoorAltHost }}
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 9080
{{- end }}
