#!/bin/bash

CONTAINERS=$(docker ps -a | grep gameon_dev_etcd-viewer)
if [ -n "$CONTAINERS" ]; then
  docker stop -t 0 gameon_dev_etcd-viewer
  docker rm gameon_dev_etcd-viewer
fi

docker run -d --link gameon_dev_etcd0:gameon-etcd \
  --name gameon_dev_etcd-viewer \
  -p 8443 \
  registry.eu-gb.bluemix.net/gameontext/gameon-etcd-viewer
