apiVersion: v1
kind: Service
metadata:
  name: map
  namespace: gameon-system
  labels:
    app: gameon-map
spec:
  type: ClusterIP
  ports:
    - port: 9080
  selector:
    app: gameon-map
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: map
  namespace: gameon-system
  labels:
    app: gameon-map
spec:
  template:
    metadata:
      labels:
        app: gameon-map
    spec:
      volumes:
        - name: certificate
          secret:
            secretName: global-cert
      containers:
      - image: gameontext/gameon-map:latest
        imagePullPolicy: Always
        name: map
        ports:
          - containerPort: 9080
            name: map
        volumeMounts:
          - name: certificate
            mountPath: /etc/cert
        envFrom:
          - configMapRef:
              name: global-config
