apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gameon-frontdoor
  namespace: gameon-system
spec:
  gateways:
  - gameon-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /auth
    route:
    - destination:
        host: auth-service.gameon-system.svc.cluster.local
  - match:
    - uri:
        prefix: /map
    route:
    - destination:
        host: map-service.gameon-system.svc.cluster.local
  - websocketUpgrade: true
    match:
    - uri:
        prefix: /mediator/ws
    route:
    - destination:
        host: mediator-service.gameon-system.svc.cluster.local
  - match:
    - uri:
        prefix: /mediator
    route:
    - destination:
        host: mediator-service.gameon-system.svc.cluster.local
  - match:
    - uri:
        prefix: /players
    route:
    - destination:
        host: player-service.gameon-system.svc.cluster.local
  - websocketUpgrade: true
    match:
    - uri:
        prefix: /rooms/ws
    route:
    - destination:
        host: room-service.gameon-system.svc.cluster.local
  - match:
    - uri:
        prefix: /rooms
    route:
    - destination:
        host: room-service.gameon-system.svc.cluster.local
  - match:
    - uri:
        exact: /swagger
    redirect: 
        uri: /swagger/
  - match:
    - uri:
        prefix: /swagger/
    route:
    - destination:
        host: swagger-service.gameon-system.svc.cluster.local
  - route:
    - destination:
        host: webapp-service.gameon-system.svc.cluster.local
