apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gameon-frontdoor
  namespace: gameon-system
spec:
  gateways:
  - gameon-gateway
  hosts:
  - '*'
  http:
  - name: "auth-route"
    match:
    - uri:
        prefix: "/auth"
    route:
    - destination:
        host: auth.gameon-system.svc.cluster.local
  - name: "map-route"
    match:
    - uri:
        prefix: "/map"
    route:
    - destination:
        host: map.gameon-system.svc.cluster.local
  - name: "mediator-route"
    match:
    - uri:
        prefix: "/mediator"
    route:
    - destination:
        host: mediator.gameon-system.svc.cluster.local
  - name: "players-route"
    match:
    - uri:
        prefix: "/players"
    route:
    - destination:
        host: player.gameon-system.svc.cluster.local
  - name: "rooms-route"
    match:
    - uri:
        prefix: "/rooms"
    route:
    - destination:
        host: room.gameon-system.svc.cluster.local
  - name: "swagger-redirect"
    match:
    - uri:
        exact: "/swagger"
    redirect:
        uri: "/swagger/"
  - name: "swagger-route"
    match:
    - uri:
        prefix: "/swagger/"
    route:
    - destination:
        host: swagger.gameon-system.svc.cluster.local
  - route:
    - destination:
        host: webapp.gameon-system.svc.cluster.local
