kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: gameon-ingress
  namespace: gameon-system
spec:
  tls:
    - hosts:
      - GAMEON_INGRESS
    secretName: GAMEON_INGRESS_SECRET
  rules:
  - host: GAMEON_INGRESS
    http:
      paths:
      - path: /auth
        backend:
          serviceName: auth
          servicePort: 9080
      - path: /players
        backend:
          serviceName: player
          servicePort: 9080
      - path: /mediator
        backend:
          serviceName: mediator
          servicePort: 9080
      - path: /map
        backend:
          serviceName: map
          servicePort: 9080
      - path: /rooms
        backend:
          serviceName: room
          servicePort: 9080
      - path: /
        backend:
          serviceName: webapp
          servicePort: 8080
