global:
  frontDoor: GAME_FRONT_DOOR
  frontDoorHost: GAMEON_INGRESS
  mode: development
  includeIPRanges: GAMEON_INTERNAL_IPRANGE
  data:
# Global: interservice communication
    MAP_SERVICE_URL: http://map.gameon-system.svc.cluster.local:9080/map/v1/sites
    MAP_HEALTH_SERVICE_URL: http://map.gameon-system.svc.cluster.local:9080/map/v1/health
    PLAYER_SERVICE_URL: http://player.gameon-system.svc.cluster.local:9080/players/v1/accounts
    RECROOM_SERVICE_URL: wss://GAME_FRONT_DOOR/rooms
# Global: Common backing services
    COUCHDB_SERVICE_URL: http://couchdb.gameon-system.svc.cluster.local:5984
    COUCHDB_HOST_AND_PORT: couchdb.gameon-system.svc.cluster.local:5984
    KAFKA_SERVICE_URL: kafka.gameon-system.svc.cluster.local:9092
# Global configuration vars for running locally
    TARGET_PLATFORM: local

globalsecrets:
  data:
    COUCHDB_USER: mapUser
    COUCHDB_PASSWORD: myCouchDBSecret
    MESSAGEHUB_USER: ''
    MESSAGEHUB_PASSWORD: ''
    SYSTEM_ID: game-on.org
    ADMIN_PASSWORD: admin
    MAP_KEY: fish
    SWEEP_ID: sweep
    SWEEP_SECRET: sweepSecret

auth:
  data:
    FACEBOOK_APP_ID: ''
    FACEBOOK_APP_SECRET: ''
    GITHUB_APP_ID: ''
    GITHUB_APP_SECRET: ''
    GOOGLE_APP_ID: ''
    GOOGLE_APP_SECRET: ''
    TWITTER_CONSUMER_KEY: ''
    TWITTER_CONSUMER_SECRET: ''

ingress:
  enabled: GAMEON_NO_ISTIO
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
  - hosts:
    - GAMEON_INGRESS
  secretName: GAMEON_INGRESS_SECRET
#  Define default backend for the ingress
  backend:
    serviceName: webapp
    servicePort: 8080

####
# Core services:
# Used to generate core service & deployment artifacts
#
# Specify imagePullPolicy per item, or rely on default behavior
# see templates/coreservice.yaml and templates/coredeployment.yaml
coreServices:
# auth service
- serviceName: auth
  servicePort: 9080
  path: /auth
  image: gameontext/gameon-auth:lastgood
  configMapRef:
  - gameon-system-auth-config
  readinessProbe:
    path: /auth/health
    initialDelaySeconds: 40
# map service
- serviceName: map
  servicePort: 9080
  path: /map
  image: gameontext/gameon-map:lastgood
  readinessProbe:
    path: /map/v1/health
    initialDelaySeconds: 40
# mediator service
- serviceName: mediator
  servicePort: 9080
  path: /mediator
  image: gameontext/gameon-mediator:lastgood
  readinessProbe:
    path: /mediator/
    initialDelaySeconds: 40
# player service
- serviceName: player
  servicePort: 9080
  path: /players
  image: gameontext/gameon-player:lastgood
  readinessProbe:
    path: /players/v1/health
    initialDelaySeconds: 40
# swagger service
- serviceName: swagger
  servicePort: 8080
  path: /swagger/
  image: gameontext/gameon-swagger:lastgood
  readinessProbe:
    path: /
    initialDelaySeconds: 40
# room service
- serviceName: room
  servicePort: 9080
  path: /rooms
  image: gameontext/gameon-room:lastgood
  readinessProbe:
    path: /rooms/
    initialDelaySeconds: 40
# webapp service
- serviceName: webapp
  servicePort: 8080
  skipIngress: true
  path: /
  image: gameontext/gameon-webapp:lastgood
  readinessProbe:
    path: /health
    initialDelaySeconds: 40
