apiVersion: v1
kind: Secret
metadata:
  name: global-secret
  namespace: gameon-system
stringData:
  COUCHDB_USER: mapUser
  COUCHDB_PASSWORD: myCouchDBSecret
  MESSAGEHUB_USER: ''
  MESSAGEHUB_PASSWORD: ''
  SYSTEM_ID: game-on.org
  ADMIN_PASSWORD: admin
  MAP_KEY: fish
  SWEEP_ID: sweep
  SWEEP_SECRET: sweepSecret
# Auth service environment variables
  FACEBOOK_APP_ID: ''
  FACEBOOK_APP_SECRET: ''
  GITHUB_APP_ID: ''
  GITHUB_APP_SECRET: ''
  GOOGLE_APP_ID: ''
  GOOGLE_APP_SECRET: ''
  TWITTER_CONSUMER_KEY: ''
  TWITTER_CONSUMER_SECRET: ''