global:
  frontDoor: GAMEON_INGRESS
  mode: development
  data:
# Global: interservice communication
    MAP_SERVICE_URL: http://map-service.gameon-system.svc.cluster.local:9080/map/v1/sites
    MAP_HEALTH_SERVICE_URL: http://map-service.gameon-system.svc.cluster.local:9080/map/v1/health
    PLAYER_SERVICE_URL: http://player-service.gameon-system.svc.cluster.local:9080/players/v1/accounts
    RECROOM_SERVICE_URL: ws://room-service.gameon-system.svc.cluster.local:9080/rooms
# Global: Common backing services
    COUCHDB_USER: mapUser
    COUCHDB_PASSWORD: myCouchDBSecret
    COUCHDB_SERVICE_URL: http://couchdb-service.gameon-system.svc.cluster.local:5984
    COUCHDB_HOST_AND_PORT: couchdb-service.gameon-system.svc.cluster.local:5984
    KAFKA_SERVICE_URL: kafka-service.gameon-system.svc.cluster.local:9092
    MESSAGEHUB_USER: ''
    MESSAGEHUB_PASSWORD: ''
  development:
# Global configuration vars for running locally
    TARGET_PLATFORM: local
    SYSTEM_ID: game-on.org
    ADMIN_PASSWORD: admin
    MAP_KEY: fish
    SWEEP_ID: sweep
    SWEEP_SECRET: sweepSecret

auth:
  data:
    FACEBOOK_APP_ID: ''
    FACEBOOK_APP_SECRET: ''
    GITHUB_APP_ID: ''
    GITHUB_APP_SECRET: ''
    GOOGLE_APP_ID: ''
    GOOGLE_APP_SECRET: ''
    TWITTER_CONSUMER_KEY: ''
    TWITTER_CONSUMER_SECRET: ''

ingress:
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    - hosts:
        - GAMEON_INGRESS_SECRET
      secretName: GAMEON_INGRESS_SECRET

# Core services: Used to generate core service & deployment artifacts
# Specify imagePullPolicy per item, or rely on default behavior
# see templates/coreservice.yaml and templates/coredeployment.yaml
coreServices:
# auth service
  - serviceName: auth
    servicePort: 9080
    path: /auth
    image: gameontext/gameon-auth:latest
    configMapRef:
      - gameon-system-auth-config
    readinessProbe:
      path: /auth/health
      initialDelaySeconds: 40
# map service
  - serviceName: map
    servicePort: 9080
    path: /map
    image: gameontext/gameon-map:latest
    readinessProbe:
      path: /map/v1/health
      initialDelaySeconds: 40
# mediator service
  - serviceName: mediator
    servicePort: 9080
    path: /mediator
    image: gameontext/gameon-mediator:latest
    readinessProbe:
      path: /mediator/
      initialDelaySeconds: 20
# player service
  - serviceName: player
    servicePort: 9080
    path: /players
    image: gameontext/gameon-player:latest
    readinessProbe:
      path: /players/v1/health
      initialDelaySeconds: 20
# swagger service
  - serviceName: swagger
    servicePort: 8080
    path: /
    image: gameontext/gameon-swagger:lastgood
    readinessProbe:
      path: /
      initialDelaySeconds: 20
# room service
  - serviceName: room
    servicePort: 9080
    path: /rooms
    image: gameontext/gameon-room:latest
    readinessProbe:
      path: /
      initialDelaySeconds: 40
# webapp service
  - serviceName: webapp
    servicePort: 8080
    path: /
    image: gameontext/gameon-webapp:latest
    readinessProbe:
      path: /health
      initialDelaySeconds: 40
